(TeX-add-style-hook "ThesisTemplate"
 (lambda ()
    (LaTeX-add-bibliographies
     "main")
    (LaTeX-add-labels
     "sec:equations"
     "eq:alphaoverbeta"
     "eq:anothersillyequation"
     "fig:example"
     "fig:example2"
     "sec:blahblah")
    (TeX-add-symbols
     "authorfirst"
     "authorMI"
     "authorlast"
     "degreefull"
     "degreeshort"
     "dept"
     "institution"
     "thesistitle"
     "pdfsubject"
     "pdfkeywords"
     "yearcomplete"
     "thesisdirector"
     "thesisdirectortitle"
     "deptchair"
     "deptchairtitle"
     "dean"
     "deantitle"
     "fecone"
     "fectwo"
     "fecthree")
    (TeX-run-style-hooks
     "cite"
     "overcite"
     "natbib"
     "WSU"
     "latex2e"
     "rep12"
     "report"
     "12pt")))

